-- MySQL Script generated by MySQL Workbench
-- Mon Sep 23 19:02:16 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hospitalfrenz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospitalfrenz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospitalfrenz` DEFAULT CHARACTER SET latin1 ;
USE `hospitalfrenz` ;

-- -----------------------------------------------------
-- Table `hospitalfrenz`.`coberturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitalfrenz`.`coberturas` (
  `IDCobertura` INT(11) NOT NULL,
  `NombreCobertura` VARCHAR(20) NOT NULL,
  `TipoCobertura` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`IDCobertura`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hospitalfrenz`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitalfrenz`.`usuarios` (
  `DNI` INT(11) NOT NULL,
  `NombreUser` VARCHAR(20) NOT NULL,
  `EmailUser` VARCHAR(40) NOT NULL,
  `ContraseniaUser` VARCHAR(20) NOT NULL,
  `AdminUser` TINYINT(4) NOT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hospitalfrenz`.`medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitalfrenz`.`medicos` (
  `MatriculaMed` INT(11) NOT NULL,
  `NombreMed` VARCHAR(20) NOT NULL,
  `ApellidosMed` VARCHAR(20) NOT NULL,
  `NombreUser` VARCHAR(20) NOT NULL,
  `DNIMed` INT(11) NOT NULL,
  `DireccionMed` VARCHAR(40) NULL DEFAULT NULL,
  `Localidad` VARCHAR(40) NULL DEFAULT NULL,
  `ProvinciaMed` VARCHAR(40) NULL DEFAULT NULL,
  `TelefonoMed` INT(11) NOT NULL,
  `EstadoMed` TINYINT(4) NOT NULL,
  PRIMARY KEY (`MatriculaMed`),
  INDEX `FK_Medicos_MedUser` (`DNIMed` ASC) VISIBLE,
  CONSTRAINT `FK_Medicos_MedUser`
    FOREIGN KEY (`DNIMed`)
    REFERENCES `hospitalfrenz`.`usuarios` (`DNI`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hospitalfrenz`.`cobxmed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitalfrenz`.`cobxmed` (
  `IDMatriculaMed` INT(11) NOT NULL,
  `IDCobertura` INT(11) NOT NULL,
  PRIMARY KEY (`IDMatriculaMed`, `IDCobertura`),
  INDEX `FK_CobXMed_IDCob` (`IDCobertura` ASC) VISIBLE,
  CONSTRAINT `FK_CobXMed_IDCob`
    FOREIGN KEY (`IDCobertura`)
    REFERENCES `hospitalfrenz`.`coberturas` (`IDCobertura`),
  CONSTRAINT `FK_CobXMed_MatMed`
    FOREIGN KEY (`IDMatriculaMed`)
    REFERENCES `hospitalfrenz`.`medicos` (`MatriculaMed`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hospitalfrenz`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitalfrenz`.`especialidades` (
  `NumEspecialidad` INT(11) NOT NULL,
  `DescripcionEspecialidad` VARCHAR(40) NOT NULL,
  `EstadoEspecialidad` TINYINT(4) NOT NULL,
  PRIMARY KEY (`NumEspecialidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hospitalfrenz`.`espxmed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitalfrenz`.`espxmed` (
  `IDMatriculaMed` INT(11) NOT NULL,
  `NumEspecialidad` INT(11) NOT NULL,
  PRIMARY KEY (`IDMatriculaMed`, `NumEspecialidad`),
  INDEX `FK_espxmed_NumEsp` (`NumEspecialidad` ASC) VISIBLE,
  CONSTRAINT `FK_espxmed_IDMatMed`
    FOREIGN KEY (`IDMatriculaMed`)
    REFERENCES `hospitalfrenz`.`medicos` (`MatriculaMed`),
  CONSTRAINT `FK_espxmed_NumEsp`
    FOREIGN KEY (`NumEspecialidad`)
    REFERENCES `hospitalfrenz`.`especialidades` (`NumEspecialidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hospitalfrenz`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitalfrenz`.`pacientes` (
  `DNIPaciente` INT(11) NOT NULL,
  `NombrePaciente` VARCHAR(20) NOT NULL,
  `ApellidoPaciente` VARCHAR(20) NOT NULL,
  `NombreUser` VARCHAR(20) NOT NULL,
  `FechaNacPaciente` DATE NOT NULL,
  `Telefono` INT(11) NOT NULL,
  `DireccionPaciente` VARCHAR(40) NULL DEFAULT NULL,
  `LocalidadPaciente` VARCHAR(40) NULL DEFAULT NULL,
  `ProvinciaPaciente` VARCHAR(40) NULL DEFAULT NULL,
  `IDCobertura` INT(11) NOT NULL,
  `EstadoPaciente` TINYINT(4) NOT NULL,
  PRIMARY KEY (`DNIPaciente`),
  INDEX `FK_Pacientes_PacCob` (`IDCobertura` ASC) VISIBLE,
  CONSTRAINT `FK_Pacientes_PacCob`
    FOREIGN KEY (`IDCobertura`)
    REFERENCES `hospitalfrenz`.`coberturas` (`IDCobertura`),
  CONSTRAINT `FK_Pacientes_PacUser`
    FOREIGN KEY (`DNIPaciente`)
    REFERENCES `hospitalfrenz`.`usuarios` (`DNI`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hospitalfrenz`.`sedes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitalfrenz`.`sedes` (
  `IDSede` INT(11) NOT NULL,
  `NombreSede` VARCHAR(20) NOT NULL,
  `DireccionSede` VARCHAR(40) NOT NULL,
  `LocalidadSede` VARCHAR(40) NOT NULL,
  `ProvinciaSede` VARCHAR(40) NOT NULL,
  `Estado` TINYINT(4) NOT NULL,
  PRIMARY KEY (`IDSede`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hospitalfrenz`.`turnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitalfrenz`.`turnos` (
  `IDTurno` INT(11) NOT NULL,
  `IDSede` INT(11) NOT NULL,
  `IDMatriculaMed` INT(11) NOT NULL,
  `DNIPaciente` INT(11) NOT NULL,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `NumEspecialidad` INT(11) NOT NULL,
  `Estado` TINYINT(4) NOT NULL,
  PRIMARY KEY (`IDTurno`, `IDSede`, `DNIPaciente`, `IDMatriculaMed`),
  INDEX `FK_Turnos_MatMed` (`IDMatriculaMed` ASC) VISIBLE,
  INDEX `FK_Turnos_DNIPac` (`DNIPaciente` ASC) VISIBLE,
  INDEX `FK_Turnos_IDSede` (`IDSede` ASC) VISIBLE,
  INDEX `FK_Turnos_NumEsp` (`NumEspecialidad` ASC) VISIBLE,
  CONSTRAINT `FK_Turnos_DNIPac`
    FOREIGN KEY (`DNIPaciente`)
    REFERENCES `hospitalfrenz`.`pacientes` (`DNIPaciente`),
  CONSTRAINT `FK_Turnos_IDSede`
    FOREIGN KEY (`IDSede`)
    REFERENCES `hospitalfrenz`.`sedes` (`IDSede`),
  CONSTRAINT `FK_Turnos_MatMed`
    FOREIGN KEY (`IDMatriculaMed`)
    REFERENCES `hospitalfrenz`.`medicos` (`MatriculaMed`),
  CONSTRAINT `FK_Turnos_NumEsp`
    FOREIGN KEY (`NumEspecialidad`)
    REFERENCES `hospitalfrenz`.`especialidades` (`NumEspecialidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hospitalfrenz`.`historialxpac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitalfrenz`.`historialxpac` (
  `IDTurno` INT(11) NOT NULL,
  `IDMatriculaMed` INT(11) NOT NULL,
  `DNIPaciente` INT(11) NOT NULL,
  `IDSede` INT(11) NOT NULL,
  `NumEspecialidad` INT(11) NULL DEFAULT NULL,
  `Hora` TIME NOT NULL,
  `Fecha` DATE NOT NULL,
  `Estado` TINYINT(4) NOT NULL,
  `Asistencia` TINYINT(4) NOT NULL,
  PRIMARY KEY (`IDTurno`, `IDSede`),
  INDEX `FK_HistorialXPac_MatMed` (`IDMatriculaMed` ASC) VISIBLE,
  INDEX `FK_HistorialXPac_DNIPac` (`DNIPaciente` ASC) VISIBLE,
  INDEX `FK_HistorialXPac_Sede` (`IDSede` ASC) VISIBLE,
  INDEX `FK_HistorialXPac_Especialidad` (`NumEspecialidad` ASC) VISIBLE,
  CONSTRAINT `FK_HistorialXPac_DNIPac`
    FOREIGN KEY (`DNIPaciente`)
    REFERENCES `hospitalfrenz`.`pacientes` (`DNIPaciente`),
  CONSTRAINT `FK_HistorialXPac_Especialidad`
    FOREIGN KEY (`NumEspecialidad`)
    REFERENCES `hospitalfrenz`.`especialidades` (`NumEspecialidad`),
  CONSTRAINT `FK_HistorialXPac_MatMed`
    FOREIGN KEY (`IDMatriculaMed`)
    REFERENCES `hospitalfrenz`.`medicos` (`MatriculaMed`),
  CONSTRAINT `FK_HistorialXPac_Sede`
    FOREIGN KEY (`IDSede`)
    REFERENCES `hospitalfrenz`.`sedes` (`IDSede`),
  CONSTRAINT `FK_HistorialXPac_Turno`
    FOREIGN KEY (`IDTurno`)
    REFERENCES `hospitalfrenz`.`turnos` (`IDTurno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hospitalfrenz`.`medxsed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitalfrenz`.`medxsed` (
  `IDSede` INT(11) NOT NULL,
  `IDMatriculaMed` INT(11) NOT NULL,
  PRIMARY KEY (`IDSede`, `IDMatriculaMed`),
  INDEX `FK_MedXSed_IDMatMed` (`IDMatriculaMed` ASC) VISIBLE,
  CONSTRAINT `FK_MedXSed_IDMatMed`
    FOREIGN KEY (`IDMatriculaMed`)
    REFERENCES `hospitalfrenz`.`medicos` (`MatriculaMed`),
  CONSTRAINT `FK_MedXSed_IDSede`
    FOREIGN KEY (`IDSede`)
    REFERENCES `hospitalfrenz`.`sedes` (`IDSede`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
